env: dev

logging:
  config:
    classpath: logback-spring.xml

server:
  port: 8083
  servlet:
    context-path: /cloud-server

eureka:
  instance:
    hostname: localhost
  client:
    # 以下两项一定要是false，表明自己是服务器，而不需要从其他主机发现服务
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/