env: dev

logging:
  config:
    classpath: logback-spring.xml

server:
  port: 8086

spring:
  application:
    name: CLOUD-CONFIG
  profiles:
    active: native
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/TheChildHisDad/cloud-hoxton-config.git
#          search-paths: cloud-hoxton-config
#          force-pull: true
#          default-label: master
#          username: 10*****@qqww.com
#          password: ******
        native:
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/cloud-server/eureka
  instance:
    prefer-ip-address: true